apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: container-app-demo
          image: 719227682233.dkr.ecr.us-east-1.amazonaws.com/app-demo:latest
          ports:
            - containerPort: 80
