apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
        - name: mi-contenedor
          image: 719227682233.dkr.ecr.us-east-1.amazonaws.com/app-demo:latest
          ports:
            - containerPort: 80
